# Generated by Django 5.2.5 on 2025-09-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
    ]
