# Generated by Django 5.2.5 on 2025-09-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_rename_score_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
    ]
